import { createWorkflow, WorkflowResponse } from "@medusajs/framework/workflows-sdk"
import { GIFT_CARD_MODULE } from "../modules/gift-card"
import GiftCardModuleService from "../modules/gift-card/service"

type WorkflowInput = {
    order_id: string
}

/**
 * Workflow to generate gift cards for an order
 * Can be called manually or from other workflows
 */
export const generateGiftCardsWorkflow = createWorkflow(
    "generate-gift-cards",
    (input: WorkflowInput) => {
        // This workflow is primarily handled by the subscriber
        // But can be used for manual generation if needed
        return new WorkflowResponse({
            success: true,
            message: "Gift cards will be generated by subscriber",
        })
    }
)

export default generateGiftCardsWorkflow
